// Küratör seçkisi — tek doğruluk kaynağı (API rotası da buradan beslenir)
export const GAMES = [
  { id: 'gates', icon: '⚡', name: 'Gates of Olympus', cat: 'risk', rtp: '96.50', vol: 'Yüksek', type: 'slot',
    note: '6×5 scatter — 8+ her yerde öder, tumble, çarpan küreleri FS’de birikir (15 FS).' },
  { id: 'mt4', icon: '🚂', name: 'Money Train 4', cat: 'risk', rtp: '96.10', vol: 'Yüksek', type: 'slot',
    note: '5×4 Hold&Win — 3+ 💰 ile 3 can respin, para değerleri yapışır.' },
  { id: 'wdw', icon: '🤠', name: 'Wanted Dead or a Wild', cat: 'risk', rtp: '96.38', vol: 'Yüksek', type: 'slot',
    note: '5×4 VS — genişleyen wild, düello çarpanı ×2-×100.' },
  { id: 'sp', icon: '✨', name: 'Starlight Princess', cat: 'calm', rtp: '96.50', vol: 'Orta-Düşük', type: 'slot',
    note: '6×5 scatter Starlight — tumble + ışın çarpanları birikir (15 FS).' },
  { id: 'sb', icon: '🍬', name: 'Sweet Bonanza', cat: 'calm', rtp: '96.48', vol: 'Orta', type: 'slot',
    note: '6×5 şeker — 8+ öder, tumble, bomba çarpanlar FS’de birikir (10 FS).' },
  { id: 'bs', icon: '🦇', name: 'Blood Suckers', cat: 'calm', rtp: '98.00', vol: 'Düşük', type: 'slot',
    note: '5×3 25 çizgi — 3+ 🩸 tabut bonusu, en yüksek RTP.' },
  { id: 'aviator', icon: '✈️', name: 'Aviator', cat: 'adren', rtp: '97.00', vol: 'Crash', type: 'crash',
    note: 'Seçkideki tek crash oyunu — Dürtü bilinçli seçti.' },
  { id: 'plinko', icon: '🟢', name: 'Plinko Original', cat: 'orig', rtp: '99.00', vol: 'Ayarlanabilir', type: 'plinko',
    note: 'Çivi piramidinden süzülen toplar — 8-16 satır ve 1000× dev çarpan.' },
  { id: 'limbo', icon: '🚀', name: 'Limbo Rocket', cat: 'adren', rtp: '99.00', vol: 'Yüksek Tavan', type: 'limbo',
    note: 'Hedef çarpanını belirle, anında roketle — 10.000× limitli saf şans.' },
  { id: 'bj', icon: '🂡', name: 'VIP Blackjack Masası', cat: 'strat', rtp: '99.40', vol: 'Masa', type: 'table',
    note: 'Canlı kumaş masa, Split, Double Down ve Sigorta seçenekleriyle otantik deneyim.' },
  { id: 'rl', icon: '🎡', name: 'Avrupa Rulet Masası', cat: 'strat', rtp: '97.30', vol: 'Masa', type: 'roulette',
    note: 'Gerçek kumaş örtü üzerinde tam bahis yerleşimi, dönen çark ve bilye fiziği.' },
  { id: 'mines', icon: '💣', name: 'Mines Deluxe', cat: 'adren', rtp: '97.00', vol: 'Tarla', type: 'mines',
    note: '5×5 metal karo — artan basamaklı kristal sesleri ve dinamik elmas çarpanları.' },
  { id: 'hilo', icon: '🃏', name: 'Hi-Lo Yüksek/Düşük', cat: 'orig', rtp: '98.00', vol: 'Seri Strateji', type: 'hilo',
    note: 'Sonraki kart büyük mü küçük mü? Olasılıklar canlı hesaplanır, kazanç zinciri birikir.' },
  { id: 'wheel', icon: '🎯', name: 'Şans Çarkı (Wheel)', cat: 'orig', rtp: '98.50', vol: 'Çoklu Kademe', type: 'wheel',
    note: 'Özel segmentler, tıkırdayan ibre ve 50× çarpanlı çark deneyimi.' },
  { id: 'sport', icon: '🏆', name: 'Spor Bahsi — Gerçek Kupon', cat: 'strat', rtp: '94.50', vol: 'Spor', type: 'sport',
    note: '3 maç · 1X2 · küratörlü oranlar; sonuç oranların ima ettiği olasılıkla ağırlıklı simüle edilir.' },
];

export const CATS = [
  ['all', 'Tümü'],
  ['orig', '💎 Orijinaller'],
  ['risk', '🎩 Yüksek Risk'],
  ['calm', '🍷 Uzun Akşam'],
  ['adren', '⚡ Adrenalin'],
  ['strat', '🎯 Stratejist'],
];
